//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MROInventory_Project.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Notification_MROSoap")]
    public interface Notification_MROSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        MROInventory_Project.ServiceReference1.HelloWorldResponse HelloWorld(MROInventory_Project.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<MROInventory_Project.ServiceReference1.HelloWorldResponse> HelloWorldAsync(MROInventory_Project.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Notification_Caducidad", ReplyAction="*")]
        void Notification_Caducidad(int test);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Notification_Caducidad", ReplyAction="*")]
        System.Threading.Tasks.Task Notification_CaducidadAsync(int test);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public MROInventory_Project.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(MROInventory_Project.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public MROInventory_Project.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(MROInventory_Project.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Notification_MROSoapChannel : MROInventory_Project.ServiceReference1.Notification_MROSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Notification_MROSoapClient : System.ServiceModel.ClientBase<MROInventory_Project.ServiceReference1.Notification_MROSoap>, MROInventory_Project.ServiceReference1.Notification_MROSoap {
        
        public Notification_MROSoapClient() {
        }
        
        public Notification_MROSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Notification_MROSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Notification_MROSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Notification_MROSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MROInventory_Project.ServiceReference1.HelloWorldResponse MROInventory_Project.ServiceReference1.Notification_MROSoap.HelloWorld(MROInventory_Project.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            MROInventory_Project.ServiceReference1.HelloWorldRequest inValue = new MROInventory_Project.ServiceReference1.HelloWorldRequest();
            inValue.Body = new MROInventory_Project.ServiceReference1.HelloWorldRequestBody();
            MROInventory_Project.ServiceReference1.HelloWorldResponse retVal = ((MROInventory_Project.ServiceReference1.Notification_MROSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MROInventory_Project.ServiceReference1.HelloWorldResponse> MROInventory_Project.ServiceReference1.Notification_MROSoap.HelloWorldAsync(MROInventory_Project.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<MROInventory_Project.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            MROInventory_Project.ServiceReference1.HelloWorldRequest inValue = new MROInventory_Project.ServiceReference1.HelloWorldRequest();
            inValue.Body = new MROInventory_Project.ServiceReference1.HelloWorldRequestBody();
            return ((MROInventory_Project.ServiceReference1.Notification_MROSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public void Notification_Caducidad(int test) {
            base.Channel.Notification_Caducidad(test);
        }
        
        public System.Threading.Tasks.Task Notification_CaducidadAsync(int test) {
            return base.Channel.Notification_CaducidadAsync(test);
        }
    }
}
